# Generated by Django 3.1.4 on 2020-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.DateTimeField(choices=[('8:00 - 9:00', '8:00 - 9:00'), ('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00')])),
                ('patient', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('Konsultacja', 'Konsultacja'), ('Interwencja', 'Interwencja'), ('Operacja', 'Operacja')], max_length=64)),
            ],
            options={
                'unique_together': {('day', 'hour')},
            },
        ),
    ]
