# Generated by Django 3.1.4 on 2020-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_dent', '0002_auto_20201230_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='hour',
            field=models.CharField(choices=[('8-9', '8:00 - 9:00'), ('9-10', '9:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('12-13', '12:00 - 13:00'), ('13-14', '13:00 - 14:00'), ('14-15', '14:00 - 15:00'), ('15-16', '15:00 - 16:00')], help_text='Podaj godzinę wizyty', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set(),
        ),
    ]
