# Generated by Django 3.1.4 on 2021-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_dent', '0005_auto_20210102_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AddField(
            model_name='visit',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='mail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hour',
            field=models.CharField(choices=[('8-9', '8:00 - 9:00'), ('9-10', '9:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('12-13', '12:00 - 13:00'), ('13-14', '13:00 - 14:00'), ('14-15', '14:00 - 15:00'), ('15-16', '15:00 - 16:00')], help_text='Podaj godzinę wizyty', max_length=64),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.CharField(choices=[('Konsultacja', 'Konsultacja'), ('Interwencja', 'Interwencja'), ('Operacja', 'Operacja')], max_length=64),
        ),
    ]
