# Generated by Django 3.1.4 on 2021-01-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_dent', '0006_auto_20210103_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone',
            field=models.CharField(blank=True, default=48505466623, max_length=17, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi zawierać się w formacie: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
