# Generated by Django 3.1.4 on 2021-01-03 15:44

from django.db import migrations, models
import rent_a_dent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_dent', '0007_auto_20210103_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='day',
            field=models.DateField(validators=[rent_a_dent.models.no_pass_date]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hour',
            field=models.CharField(choices=[('8-9', '8:00 - 9:00'), ('9-10', '9:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('12-13', '12:00 - 13:00'), ('13-14', '13:00 - 14:00'), ('14-15', '14:00 - 15:00'), ('15-16', '15:00 - 16:00')], max_length=64),
        ),
    ]
